const dev = {
  env: 'dev',
  hostname: 'localhost',
  port: 3000,
  protocol: 'http',
  apiEndpoint: 'https://dev-api.kpc-dev.com',
  facebookAppId: '1976699389266498',
  gtmId: 'GTM-TVTVFVV',
  paymentOmisePublicKey: 'pkey_test_594z5pfxuxjisya440j',
  paymentOmise: 'https://dev-payment-gateway.kpc-dev.com/paymentgateway/charges/omise',
  paymentAlipay: 'https://dev-payment-gateway.kpc-dev.com/paymentgateway/charges/alipay',
  paymentTransactionStatus: 'https://dev-payment-gateway.kpc-dev.com/paymentgateway/transactions',
  clientSecret: '',
  errorMessageUrl: 'https://s3-ap-southeast-1.amazonaws.com/prod-kingpower-click/resources/errorMessages.json',
  googleVerificationToken: 'kbkOruycFh6NqTSq3Tr8ErS0Fb8hcttP-FD97dRcLho',
  androidAppId: 'com.kingpower.online',
  iOSAppId: '1286637638',
  sentryDNS: 'https://f1955cfada7546349509035dd456475f@sentry.kpc-dev.com/4',
  webUrl: 'https://dev-web.kpc-dev.com',
  imageHostURL: 'https://s3-ap-southeast-1.amazonaws.com/kpc-development/frontend/',
  platform: 'Web',
  micrositeResourceUrl: 'https://s3-ap-southeast-1.amazonaws.com/prod-kingpower-click/resources/',
  powerMagUrl: 'https://powermag.kingpower.com/wp-json/wp/v2/posts?categories=521&_embed',
}

const uat = {
  env: 'uat',
  hostname: 'localhost',
  port: 3000,
  protocol: 'http',
  apiEndpoint: 'https://uat-api.kpc-dev.com',
  facebookAppId: '386657328420639',
  gtmId: 'GTM-KD3QJ63',
  paymentOmisePublicKey: 'pkey_test_5aeph56z8jlmpa3ztwy',
  paymentOmise: 'https://uat-payment-gateway.kpc-dev.com/paymentgateway/charges/omise',
  paymentAlipay: 'https://uat-payment-gateway.kpc-dev.com/paymentgateway/charges/alipay',
  paymentTransactionStatus: 'https://uat-payment-gateway.kpc-dev.com/paymentgateway/transactions',
  clientSecret: '',
  errorMessageUrl: 'https://s3-ap-southeast-1.amazonaws.com/prod-kingpower-click/resources/errorMessages.json',
  googleVerificationToken: 'kbkOruycFh6NqTSq3Tr8ErS0Fb8hcttP-FD97dRcLho',
  androidAppId: 'com.kingpower.online',
  iOSAppId: '1286637638',
  sentryDNS: 'https://f1955cfada7546349509035dd456475f@sentry.kpc-dev.com/4',
  webUrl: 'https://uat-web.kpc-dev.com',
  imageHostURL: 'https://s3-ap-southeast-1.amazonaws.com/kpc-development/frontend/',
  platform: 'Web',
  micrositeResourceUrl: 'https://s3-ap-southeast-1.amazonaws.com/prod-kingpower-click/resources/',
  powerMagUrl: 'https://powermag.kingpower.com/wp-json/wp/v2/posts?categories=521&_embed',
}

module.exports = { dev, uat }
